### PR TITLE
Last part interactive list

### PR DESCRIPTION
**Pull request by joseheco**
final project

100% working

all the points pleased and working no error.

HTML
css
javascript
web pack

### CODE REVIEW

**Review by oloomoses — CHANGES_REQUESTED** [review]
Hi @joseheco, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
-  [x] You have used linter disables in all your javascript files. Instead, you should fix the issues raised since the linter enforces code quality.
Screenshot from 2022-01-15 22-53-32
Screenshot from 2022-01-15 22-53-56

- As you can see from the above screenshots, you are importing `render.js` into `index.js` and also importing `index.js` into `into render.js`. This is duplicating code and linter complains about it because it is not a good practice. Kindly look into it. Also, remember to correct other js files. 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by joseheco** [comment]
Thanks Oloo Moses for the comment, once the code has been refactored, everything is running correctly without any errors and problems, thanks for the support in slack.

**Review by oloomoses — APPROVED** [review]
Hi @joseheco, 

Well done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by marilirulita** [comment]
👋🏽

**Pull request merged**
